### ISSUE TITLE
Regenerate Behaviour Creator, if you delete a Behaviour

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#101]
If there is a behaviour Foo in the Plan Designer and you already generated code for it once, it is also listed in the BehaviourCreator.cpp/h. In case you delete Foo, its cpp/h-Files are deleted, but the BehaviourCreator still has a reference to it and the project does not compile anymore.

Current manual fix is to regenerate all files from within the Plan Designer, in order to regenerate the BehaviourCreator. 

Maybe, a better solution would be an automatic regeneration, in case a behaviour was delete.

**Comment by Schmidt1987** [comment]
Done :+1:
