### ISSUE TITLE
Too many conditions are automatically created.

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#108]
It is okay to automatically create a precondition for each transition, because otherwise this cannot be passed, or is always passed automatically.

However with regard to all other conditions of, e.g., plans, behaviours, terminal states, no condition should be created. Please revert these automatic creation of conditions here.

When you are on it, please put the creation of the transition's precondition from the do/undo method into the createTransition method of the corresonponding command class.

**Comment by Schmidt1987** [comment]
Done :+1:
