### ISSUE TITLE
Replace the Repository View

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#15]
Place the repository view below the file tree view, instead of right of the plan editor view.

Rational: It wastes space, as it is often not long enough to fill the whole monitor (same goes for file tree view). So the can shared the vertical space on the left side, thereby giving more space to the plan editor view with its plans.

**Comment by gatzi-fax** [comment]
Replacement Done

**Comment by StephanOpfer** [comment]
Fixed the issue regarding the initial divider position. See ff9b8e7961ae912f3bc2c0df1c6bbb871d7344c7
