### ISSUE TITLE
Make Conditions editable for Behaviours

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#19]
See #11 #12 

Behaviours can have one pre, run-time, and post condition. All should be editiable in the same manner, as pre and runtime conditions are editable within plans. So we need a dropdown menu for each of them, in order to activate them and make the condition GUI visible.

**Comment by MarcTellLindner** [comment]
Conditions are editabel for Behaviours and Plans

**Comment by StephanOpfer** [comment]
Please also create some GUI for editing Variables and Quantifiers of Conditions.

The GUI for Variables should be copied from the Variable Editing GUI of Behaviours and Plans.

**Comment by MarcTellLindner** [comment]
Variables and Quantifiers can be edited with the GUI.
The dirty-flag in the Plan or Behaviour is set.
