### ISSUE TITLE
Delete Plans, Behaviours, and Plantypes

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#24]
Through the file tree view it should be possible to delete plans, behaviours, and plantypes. 

Please note:
- It should only be possible to delete these files, if they are not references in any other file.
- In case of a plan, the pmlex file also needs to be deleted.
- The files autogenerated for the files should also be deleted.

**Comment by Schmidt1987** [comment]
Done :+1:
