### ISSUE TITLE
Entrypoint Tool

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#3]
Implement the entrypoint tool:

1. Click the icon to activate the tool: 
- icon graphically shows to be active
- mouse turns into a small entrypoint with a even small plus sign (+) at the lower right corner
2. Click as often as you need into the plan editor field:
- creates an entrypoint with member variables set to some default each time
- opens a pop up window to assign a task from the task repository to the created entrypoint
3. Click the icon to deactivate the tool:
- icon gets deactivated
- mouse turns back to normal

**Comment by Schmidt1987** [comment]
Working :+1:
