### ISSUE TITLE
Moving a state, doesn't redraw SyncTransitions that are connected to the Transitions of the State.

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#36]
Trigger the redraw of SyncTransitions, too, when moving a State.

**Comment by gatzi-fax** [comment]
can't reproduce. working fine for me

**Comment by StephanOpfer** [comment]
Procedure for reproduction:

1. Create new SyncTransition from Synchronisation to Transition
2. Move State of Transition
