### ISSUE TITLE
ViewModelManager runs into endless recursion

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#38]
If you manage to model a plan that includes itself (indirectly), the ViewModelManager's Method getViewModelElement() can run into an endless recursion. 

It should be forbidden to model such thing at all -> 

1. add check when adding plan/plantypes into states.
2. find a fix for plantype problems (they include all plans in a list)

**Comment by MarcTellLindner** [comment]
1. plans can't be added to themselves (neither directly nor indirectly)
2. plantype still contains all plans, but by changing the order of the creation of the viewmodelelements an endless recursion is prevented
