### ISSUE TITLE
Transition Tool

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#4]
Implement the transition tool:

1. Click the icon to activate the tool: 
- icon graphically shows to be active
- mouse turns into a transition icon if it hovers over a state or an empty spot in the plan editor field
2. Create a path of a new transition, by clicking on a state, clicking some bendpoints in empty spots (if wanted) and clicking on a state again (same state is also allowed):
- if the mouse hovers of some element that is not connectable with a transition (e.g. entrypoints, synctransitions, etc.), it should show this by adding some red X to the transition symbol at the lower right corner
3. Step 2 can be repeated as often as you like.
4. Click the icon to deactivate the tool:
- icon gets deactivated
- mouse turns back to normal

**Comment by gatzi-fax** [comment]
everything works now as described except the bendpoints

**Comment by StephanOpfer** [comment]
works for minimal working version
