### ISSUE TITLE
The area where you can select a state/ entrypoint is to small!

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#49]
Its very difficult to select a state, because the yellow circle is not the area were you can select it. Similar for EntryPoints.

**Comment by gatzi-fax** [comment]
I think tell fixed it with 7f09742a852b6b6a3f42ba892968110ff127ed86

**Comment by salkin-naj** [comment]
Seems to work, I will try to move the click point of the tool-cursors to better positions than the top-left corner.
