### ISSUE TITLE
Behaviour in a State isn't drawn.

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#52]
In an initial state, the behaviour is not shown, if the behaviour is used somewhere else in the plan tree. (Probably an issue with the cycle detection from @MarcTellLindner)

**Comment by StephanOpfer** [comment]
Seems to be fixed with fc37a95ae5eef7c1ba210e321267dda2662ad61b

Please confirm.

**Comment by MarcTellLindner** [comment]
Bug still exists and affects all kinds of AbstractPlans in States. It seems like there is always one AstractPlan that isn't shown per Plan. (The model contains it though, because it can't be added to the State again)

**Comment by MarcTellLindner** [comment]
Bug was caused by the way references to an AbstractPlan in a State were resolved when the model is loaded
