### ISSUE TITLE
RegisterDirtyFlag for Cross-File References

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#53]
For the following cases (and probably I forgot some), it is necessary to set the DirtyFlag to "TRUE", if the name property changes for some element that is referenced:
- Name of Plans, Behaviours, and PlanTypes in States -> Parent Plan gets dirty, too.
- Name of Plans in PlanTypes -> AnnotatedPlan references other Plan and should make the PlanType get dirty, too.
- Name of Taskrepository -> Every Plan that references a Task from that Taskrepository should get dirty, too.

**Comment by StephanOpfer** [comment]
The used listeners should be unregistered, in case the references are removed.

**Comment by MarcTellLindner** [comment]
Is solved already by serializing all usages when renaming Plan, Behaviour, Plantype or Taskrepository
