### ISSUE TITLE
Create Configurations for Behaviours

### ISSUE THREAD

**Issue by MarcTellLindner** [dasys-lab/alica-plan-designer-fx#56]
Each Behaviour can have multiple Configurations. Instead of Behaviours these Configurations can be added to the List of AbstactPlans in a State. When a Behaviour is dragged into a State in the GUI, this Behaviours default Configuration is added to the State. Afterwards another Configuration of this Behaviour can be chosen or a new one can be created.

**Comment by MarcTellLindner** [comment]
What is done:
1. Configurations exist in Model and ViewModel
2. Comands exist to create/delete them
3. Commands exist to add/remove them to/from States
4. A new Tab exists that has all the functionality of these Commands

What is missing:
1. The key value pairs exist in gui and model, but cannot be created/deleted
2. There can be multiple Configurations with the same name
3. The highlighting of the currently chosen Configuration in the Tab doesn't work properly
4. The getUsages-method probably needs to consider Configurations now

**Comment by gatzi-fax** [comment]
I changed the GUI, so you have different configuration tabs for behaviors and configurations.

+ What is now done:
1. key value pairs can now be added and deleted
2. highlighting (and choosing) now through radio buttons
3. key value pairs can be edited directly through the table
4. storing a plan now stores a dirty behavior too
+ What ist missing:
1. only when creating a new configuration there can't be two configurations with the same name. By editing a configuration through the properties table it is possible to name two configurations the same.

**Comment by gatzi-fax** [comment]
commit 82479db9ff588a08c885803372a071e047442e32 adds a check for naming two configurations the same.

**Comment by StephanOpfer** [comment]
Serialization seems to work! :+1: 
GUI Improvements:
* Unify GUI for Behaviour and Configuration context
* Dropdown for Configurations
* Make Key-Value-Pair editable like in Edit->Configure Window
* No Configuration TitledPane necessary
* Table does not update its size, when new Configurations are added
* Minimum Size for Configurations should be 1, although there is no Configuration

Show Usages does not work for Configurations/Behaviours anymore.

**Comment by gatzi-fax** [comment]
GUI Improvements:

- ~~Unify GUI for Behaviour and Configuration context~~
- ~~Dropdown for Configurations -> no radio button~~
- ~~Make Key-Value-Pair editable like in Edit->Configure Window~~
- ~~No Configuration TitledPane necessary~~
- ~~Table does not update its size, when new Configurations are added~~ (table is no more)
- Minimum Size for Configurations should be 1, although there is no Configuration <-- only for old plans

TODO:
- usage function for configurations and behaviors

**Comment by gatzi-fax** [comment]
DONE:

- ~~usage function for configurations and behaviors~~
