### ISSUE TITLE
Implement keyboard short cut to save the complete model

### ISSUE THREAD

**Issue by ajahl** [dasys-lab/alica-plan-designer-fx#68]
Currently, Ctrl + S only saves elements that are dirty. But from time to time, it is useful to save the whole model, although nothing is dirty. Especially, when new fields are introduced into model objects, you wanna parse the older version and write the new fields to files, by just saving them.

**Comment by StephanOpfer** [comment]
I suggest CTRL + SHIFT + S

**Comment by gatzi-fax** [comment]
started to work on it in branch save-all
