### ISSUE TITLE
No Quantifiers for Behaviour's Precondition

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#69]
For the first version, we decided to not allow Quantifiers in Behaviour's Precondition. Please deactivate the corresponding Quantifier-UI in the Pre- and Runtime Condition Tab of the Behaviours Element Information Tab in case of Behaviours.

**Comment by Schmidt1987** [comment]
The Quantifier-UI is deactivated for Behaviours Conditions.

**Comment by Schmidt1987** [comment]
In the xxx.beh is still the Field quantifiers in all Conditions! 
TODO: For Behaviour need to deactivate Quantifiers in Conditions.

**Comment by Schmidt1987** [comment]
Behaviours has no Quantifiers in Conditions now.
