### ISSUE TITLE
Rename Behaviours, Plan, PlanTypes and Folders 

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#70]
Its similar to moving Behaviours, but only the name changes, instead of the location.

Nevertheless, generated Source-Code need to be changed, and references to the behaviour from other model elements, too. 

Although it is already possible to change the name of elements and they get saved automatically, it probably does not update all things related to this.

**Comment by Schmidt1987** [comment]
done :+1:
