### ISSUE TITLE
Delete Transitions

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#71]
It should be possible to delete Transitions:

1. select
2. press [Del]

Note that you need to delete everything that is related with the transition (except the connected States):

- Transition
- Connected PreCondition
- Regenerate Source Code for Plan of deleted Transition in order to delete the Method Stubs 

Please write it in a way, that >undo< is possible, including regenerating the old method stubs with old content.

**Comment by Schmidt1987** [comment]
Done :+1:
