### ISSUE TITLE
Initial State Connection Tool

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#8]
Implement the initial state connection tool:

1. Click the icon to activate the tool: 
- icon graphically shows to be active
- mouse turns into a initial state connection icon if it hovers over an entrypoint
2. Create an initial state connection by clicking on an entrypoint and then clicking on a state:
- if the mouse hovers over some element that is not connectable with an initial state connection (e.g. synctransitions, failure states, etc.), it should show this by adding some red X to the initial state connection symbol at the lower right corner
3. Step 2 can be repeated as often as you like.
4. Click the icon to deactivate the tool:
- icon gets deactivated
- mouse turns back to normal

**Comment by Schmidt1987** [comment]
Working :+1:

**Comment by StephanOpfer** [comment]
Still getting Nullpointer in the ModelManager. There is missing the case for InitialStateConnection (see RuntimeException).
